name: tddclean
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_generator: ^2.0.0
  internet_connection_checker_plus: ^2.0.0
  json_serializable: ^6.7.1
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.4.4
  mockito: ^5.4.2
flutter:
  uses-material-design: true
