// Mocks generated by Mockito 5.4.2 from annotations
// in tddclean/test/features/activities/data/repositories/activity_repositpry_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tddclean/core/network/info.dart' as _i6;
import 'package:tddclean/features/activities/data/models/activity_model.dart'
    as _i4;
import 'package:tddclean/features/activities/data/services/activity_local_datasource.dart'
    as _i5;
import 'package:tddclean/features/activities/data/services/activity_remote_datasource.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ActivityRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityRemoteDataSource extends _i1.Mock
    implements _i2.ActivityRemoteDataSource {
  @override
  _i3.Future<_i4.ActivityModel>? getRandomActivityByType(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomActivityByType,
          [type],
        ),
        returnValueForMissingStub: null,
      ) as _i3.Future<_i4.ActivityModel>?);
}

/// A class which mocks [ActivityLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityLocalDataSource extends _i1.Mock
    implements _i5.ActivityLocalDataSource {
  @override
  _i3.Future<void> cacheActivity(_i4.ActivityModel? activityToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheActivity,
          [activityToCache],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
